name: OpenFaaS CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install faas-cli
      run: |
        curl -sSL https://cli.openfaas.com | sudo sh

    - name: Install k3s (lightweight Kubernetes)
      run: |
        curl -sfL https://get.k3s.io | sh -
        sudo kubectl get nodes

    - name: Install OpenFaaS
      run: |
        curl -sSL https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml | sudo kubectl apply -f -
        curl -sSL https://raw.githubusercontent.com/openfaas/faas-netes/master/yaml/faas.yml | sudo kubectl apply -f -

    - name: Wait for OpenFaaS
      run: sleep 60

    - name: Get Password
      run: |
        PASSWORD=$(sudo kubectl -n openfaas get secret basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode)
        echo $PASSWORD > pass.txt

    - name: Login OpenFaaS
      run: |
        cat pass.txt | faas-cli login --username admin --password-stdin

    - name: Deploy Function
      run: |
        faas-cli up -f stack.yaml
